// <auto-generated />
using DomeoProductsDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DomeoProductsDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20260417122137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TitleRu")
                        .IsUnique();

                    b.ToTable("brands", "reference");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("categories", "reference");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.EnumValue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId", "Code")
                        .IsUnique();

                    b.ToTable("enum_values", "reference");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameRu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalCode")
                        .IsUnique();

                    b.ToTable("products", "staging");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TitleRu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("attributes", "reference");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_id");

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("EnumValueId")
                        .HasColumnType("integer")
                        .HasColumnName("enum_value_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<decimal?>("ValueNumeric")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value_numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("value_type");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("EnumValueId");

                    b.HasIndex("ProductId", "AttributeId");

                    b.ToTable("product_attribute_values", "staging", t =>
                        {
                            t.HasCheckConstraint("ck_pav_type_exclusive", "(value_type = 'Text'    AND value_text IS NOT NULL AND value_numeric IS NULL AND value_bool IS NULL AND enum_value_id IS NULL AND brand_id IS NULL) OR (value_type = 'Numeric' AND value_numeric IS NOT NULL AND value_text IS NULL AND value_bool IS NULL AND enum_value_id IS NULL AND brand_id IS NULL) OR (value_type = 'Bool'    AND value_bool IS NOT NULL AND value_text IS NULL AND value_numeric IS NULL AND enum_value_id IS NULL AND brand_id IS NULL) OR (value_type = 'Enum'    AND enum_value_id IS NOT NULL AND value_text IS NULL AND value_numeric IS NULL AND value_bool IS NULL AND brand_id IS NULL) OR (value_type = 'Brand'   AND brand_id IS NOT NULL AND value_text IS NULL AND value_numeric IS NULL AND value_bool IS NULL AND enum_value_id IS NULL)");
                        });
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("suppliers", "reference");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.SupplierOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("supplier_offers", "staging");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Category", b =>
                {
                    b.HasOne("DomeoProductsDb.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.EnumValue", b =>
                {
                    b.HasOne("DomeoProductsDb.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany("EnumValues")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Product", b =>
                {
                    b.HasOne("DomeoProductsDb.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("DomeoProductsDb.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomeoProductsDb.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomeoProductsDb.Domain.Entities.EnumValue", "EnumValue")
                        .WithMany()
                        .HasForeignKey("EnumValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DomeoProductsDb.Domain.Entities.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Brand");

                    b.Navigation("EnumValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.SupplierOffer", b =>
                {
                    b.HasOne("DomeoProductsDb.Domain.Entities.Product", "Product")
                        .WithMany("Offers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomeoProductsDb.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Product", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.ProductAttribute", b =>
                {
                    b.Navigation("EnumValues");
                });

            modelBuilder.Entity("DomeoProductsDb.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
